[package]
name = "analysis_log"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
strip_bom = "1.0.0"
serde_json = "1.0"